### ISSUE TITLE
called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by edoardottt** [lmammino/jwtinfo#34]
### Sys info:
```
Ubuntu 23.04 x86_64
Kernel: 6.2.0-36-generic
Shell: bash 5.2.15
jwtinfo 0.4.2
```

### Bug
```console
RUST_BACKTRACE=1 jwtinfo
```

```
thread 'main' panicked at /home/edoardottt/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jwtinfo-0.4.2/src/cli.rs:32:56:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::panicking::panic
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:117:5
   3: jwtinfo::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by lmammino** [comment]
Thank you so much for reporting this, @edoardottt
